import { formatShortDate } from '../utils/dateHelpers';

function ExportField({ label, value }) {
  return (
    <div className="min-w-0">
      <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-0.5 text-sm font-medium text-slate-900">{value || '—'}</p>
    </div>
  );
}

export default function ImageExportCard({ jobDate, customRemarks, selectedJobs }) {
  const dateLabel = formatShortDate(jobDate);

  return (
    <div
      className="w-[800px] max-w-none bg-white p-8 font-sans text-slate-900"
      style={{ fontFamily: 'Inter, system-ui, sans-serif' }}
    >
      <div className="rounded-lg bg-gradient-to-r from-blue-800 via-blue-700 to-blue-600 px-6 py-5 text-white">
        <p className="text-xs font-medium uppercase tracking-widest text-blue-100">
          Manufacturing Job Sheet
        </p>
        <h1 className="mt-1 text-2xl font-bold">Bhagwati Packers</h1>
        <p className="mt-1 text-sm text-blue-100">Job Date: {dateLabel}</p>
      </div>

      {customRemarks?.trim() && (
        <div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3">
          <p className="text-xs font-semibold uppercase text-amber-800">Remarks</p>
          <p className="mt-1 whitespace-pre-wrap text-sm text-amber-900">{customRemarks}</p>
        </div>
      )}

      <div className="mt-6 space-y-5">
        {selectedJobs.map((job, index) => (
          <div
            key={job.id}
            className="rounded-lg border border-slate-200 p-4"
          >
            <div className="mb-3 flex items-center justify-between border-b border-slate-100 pb-2">
              <h2 className="text-base font-bold text-blue-800">
                Job {index + 1}: {job.customerName || '—'}
              </h2>
              {job.boxId && (
                <span className="rounded bg-blue-100 px-2 py-0.5 text-xs font-bold text-blue-800">
                  {job.boxId}
                </span>
              )}
            </div>
            <div className="grid grid-cols-2 gap-3">
              <ExportField label="Customer Name" value={job.customerName} />
              <ExportField label="Box Name" value={job.boxName} />
              <ExportField label="Box ID" value={job.boxId} />
              <ExportField label="Dimensions" value={job.dimensions} />
              <ExportField label="Layers" value={job.layers} />
              <ExportField label="Reel Size" value={job.reelSize} />
              <ExportField label="Proceed to Manufacture" value={job.proceedToManufacture} />
              <ExportField label="Remarks / Notes" value={job.remarks} />
            </div>
          </div>
        ))}
      </div>

      <p className="mt-6 text-center text-xs text-slate-400">
        Generated by Bhagwati Packers Job Selector · {dateLabel}
      </p>
    </div>
  );
}
