import { formatShortDate } from '../utils/dateHelpers';
import {
  JOB_DETAIL_FIELDS,
  JOB_EXTRA_FIELDS,
  PAPER_GSM_FIELDS,
} from '../utils/jobFields';

function ExportField({ label, value }) {
  return (
    <div className="min-w-0">
      <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-0.5 text-sm font-medium text-slate-900">{value || '—'}</p>
    </div>
  );
}

function JobEditableExport({ job }) {
  const hasNoOfCuts = Boolean(job.noOfCuts?.trim());
  const hasRemarks = Boolean(job.editableRemarks?.trim());

  if (!hasNoOfCuts && !hasRemarks) return null;

  return (
    <div className="mt-3 rounded-md border border-emerald-200 bg-emerald-50/60 p-3">
      <p className="mb-2 text-[10px] font-bold uppercase tracking-wide text-emerald-800">
        Manufacturing Notes
      </p>
      <div className="space-y-2">
        {hasNoOfCuts && <ExportField label="No of Cuts" value={job.noOfCuts} />}
        {hasRemarks && (
          <div>
            <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">
              Remarks
            </p>
            <p className="mt-0.5 whitespace-pre-wrap text-sm font-medium text-slate-900">
              {job.editableRemarks}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

function JobExportDetails({ job }) {
  const visibleExtra = JOB_EXTRA_FIELDS.filter(
    ({ key }) => job[key] && key !== 'remarks',
  );

  return (
    <>
      <div className="grid grid-cols-2 gap-3">
        {JOB_DETAIL_FIELDS.map(({ key, label }) => (
          <ExportField key={key} label={label} value={job[key]} />
        ))}
      </div>

      <div className="mt-3 rounded-md border border-blue-100 bg-blue-50/50 p-3">
        <p className="mb-2 text-[10px] font-bold uppercase tracking-wide text-blue-700">
          Paper Gsm
        </p>
        <div className="grid grid-cols-5 gap-2">
          {PAPER_GSM_FIELDS.map(({ key, label }) => (
            <ExportField key={key} label={label} value={job[key]} />
          ))}
        </div>
      </div>

      {visibleExtra.length > 0 && (
        <div className="mt-3 grid grid-cols-2 gap-3">
          {visibleExtra.map(({ key, label }) => (
            <ExportField key={key} label={label} value={job[key]} />
          ))}
        </div>
      )}

      {job.remarks && (
        <div className="mt-3">
          <ExportField label="Sheet Remarks (Excel)" value={job.remarks} />
        </div>
      )}

      <JobEditableExport job={job} />
    </>
  );
}

export default function ImageExportCard({ jobDate, selectedJobs }) {
  const dateLabel = formatShortDate(jobDate);

  return (
    <div
      className="w-[900px] max-w-none bg-white font-sans text-slate-900"
      style={{ fontFamily: 'Inter, system-ui, sans-serif' }}
      data-export-root
    >
      <div data-export-section="header" className="bg-white px-8 pt-8 pb-4">
        <div className="rounded-lg bg-gradient-to-r from-blue-800 via-blue-700 to-blue-600 px-6 py-5 text-white">
          <p className="text-xs font-medium uppercase tracking-widest text-blue-100">
            Manufacturing Job Sheet
          </p>
          <h1 className="mt-1 text-2xl font-bold">Bhagwati Packers</h1>
          <p className="mt-1 text-sm text-blue-100">Job Date: {dateLabel}</p>
        </div>
      </div>

      {selectedJobs.map((job, index) => (
        <div
          key={job.id}
          data-export-section="job"
          className="bg-white px-8 py-2"
        >
          <div className="rounded-lg border border-slate-200 p-4">
            <div className="mb-3 flex items-center justify-between border-b border-slate-100 pb-2">
              <h2 className="text-base font-bold text-blue-800">
                Job {index + 1}: {job.customerName || '—'}
                {job.boxName ? ` · ${job.boxName}` : ''}
              </h2>
              {job.layers && (
                <span className="rounded bg-blue-100 px-2 py-0.5 text-xs font-bold text-blue-800">
                  {job.layers}
                </span>
              )}
            </div>
            <JobExportDetails job={job} />
          </div>
        </div>
      ))}

      <div data-export-section="footer" className="bg-white px-8 pb-8 pt-4">
        <p className="text-center text-xs text-slate-400">
          Generated by Bhagwati Packers Job Selector · {dateLabel}
        </p>
      </div>
    </div>
  );
}
